config/routes.rb
Reddit::Application.routes.draw do
  root to: "users#new"

  resources :users
  resource :session, only: [:new, :create, :destroy]
  
  resources :subs do
    resources :posts, only: [:new]
  end
  
  resources :posts, except: [:new]
  resources :comments, only: [:create, :show]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  author_id  :integer          not null
#  post_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  parent_id  :integer
#

class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id
  )
  
  belongs_to(
    :parent,
    class_name: "Comment",
    foreign_key: :parent_id,
    primary_key: :id
  )
  
  has_many(
    :children,
    class_name: "Comment",
    foreign_key: :parent_id,
    primary_key: :id
  )
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    
    flash[:comment_errors] = @comment.errors.full_messages unless @comment.save
    
    redirect_to post_url(current_post)
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_id)
  end
  
  def current_post
    @post ||= Post.find(comment_params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<ul>
  <li class="comment">
    <%= link_to comment.content, comment_url(comment) %>
     (<%= link_to comment.author.username, user_url(comment.author) %>)
     
    <%= render partial: "comments/form", locals: { post: comment.post, parent_id: comment.id } %>
    
    <% comment.children.each do |child| %>
      <%= render partial: "comments/comment", locals: { comment: child } %>
    <% end %>
  </li>
</ul>

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="POST">
    
  <%= authenticity_token %>
  
  <input type="hidden" name="comment[post_id]" value="<%= post.id %>">
  <input type="hidden" name="comment[parent_id]" value="<%= parent_id %>">
  
  <textarea name="comment[content]"></textarea>
  
  <button>Comment</button>
</form>

app/views/comments/show.html.erb
 <%= render partial: "comments/comment", locals: { comment: @comment, post: @comment.post } %>