config/routes.rb
Reddit::Application.routes.draw do
  root to: "users#new"

  resources :users
  resource :session, only: [:new, :create, :destroy]
  
  resources :subs do
    resources :posts, only: [:new]
  end
  
  resources :posts, except: [:new]
  resources :comments, only: [:create, :show]
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true
  validates :title, uniqueness: true
  
  has_many :post_subs, inverse_of: :sub
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  
  has_many(
    :posts,
    through: :post_subs,
    source: :post
  )
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderated, only: [:destroy, :edit, :update]
  before_action :ensure_logged_in, except: [:index, :show]

  def index
    @subs = Sub.all.order(:title)
  end

  def new
    @sub = current_user.moderated_subs.new
  end
  
  def create
    @sub = current_user.moderated_subs.new(sub_params)
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def show
    current_sub
  end
  
  def edit
    current_sub
  end
  
  def update
    if current_sub.update(sub_params)
      redirect_to sub_url(current_sub)
    else
      flash.now[:errors] = current_sub.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    current_sub.destroy
    
    redirect_to subs_url
  end
  
  private
  
  def ensure_moderated
    unless current_sub.moderator == current_user
      flash[:errors] = ["You are not the moderator for #{ current_sub.title }."]
      redirect_to sub_url(current_sub)
    end
  end
  
  def current_sub
    @sub ||= Sub.find(params[:id])
  end
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<form action="<%= sub.persisted? ? sub_url(sub) : subs_url %>" method="POST">
  <input type="hidden"
    name="_method"
    value="<%= sub.persisted? ? "PATCH" : "POST" %>">
    
  <%= authenticity_token %>
  
  <label>Title
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  
  <label>Description
    <textarea name="sub[description]"><%= sub.description %></textarea>
  </label>
  
  <button><%= sub.persisted? ? "Save" : "Create" %></button>
</form>

app/views/subs/edit.html.erb
<h3>Edit <%= @sub.title %></h3>
<%= render partial: 'form', locals: { sub: @sub } %>

app/views/subs/index.html.erb
<h3>Subs</h3>

<% if logged_in? %>
  <%= link_to "Create sub", new_sub_url %>
<% end %>

<ul id="subs">
<% @subs.each do |sub| %>
  <li class="sub"><%= link_to sub.title, sub_url(sub) %></li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h3>Create sub</h3>
<%= render partial: 'form', locals: { sub: @sub } %>

app/views/subs/show.html.erb
<h3><%= @sub.title %></h3>

<p><%= @sub.description %></p>

<% if @sub.moderator == current_user %>
  <%= link_to "Edit", edit_sub_url(@sub) %>
  <%= button_to "Delete", sub_url(@sub), method: :delete %>
<% end %>

<% if logged_in? %>
  <%= link_to "Add post", new_sub_post_url(@sub) %>
<% end %>

<ul>
  <% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %></li>
  <% end %>
</ul>