config/routes.rb
Reddit::Application.routes.draw do
  root to: "users#new"

  resources :users
  resource :session, only: [:new, :create, :destroy]
  
  resources :subs do
    resources :posts, only: [:new]
  end
  
  resources :posts, except: [:new]
  resources :comments, only: [:create, :show]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  url        :string(255)
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  
  validates_format_of :url, with: /\Ahttps?:\/\//i, allow_blank: true
  
  has_many :post_subs, inverse_of: :post
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )
  
  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id
  )
  
  has_many(
    :top_level_comments,
    -> { where(parent_id: nil) },
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id
  )
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_authored, only: [:edit, :update]

  def new
    @subs = Sub.all.order(:title)
    @post = current_sub.posts.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.author = current_user
    
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def edit
    @subs = Sub.all.order(:title)
    current_post
  end
  
  def update
    if current_post.update(post_params)
      redirect_to post_url(current_post)
    else
      flash.now[:errors] = current_post.errors.full_messages
      render :edit
    end
  end
  
  def show
    current_post
  end
  
  private
  
  def ensure_authored
    unless current_post.author == current_user
      flash[:errors] = ["You are not the author for #{ current_post.title }."]
      redirect_to post_url(current_post)
    end
  end
  
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
  
  def current_post
    @post ||= Post.find(params[:id])
  end
  
  def current_sub
    @sub ||= Sub.find(params[:sub_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_title(post)
    post.url == "" ? post.title : link_to(post.title, post.url)
  end
end

app/views/posts/_form.html.erb
<form action="<%= post.persisted? ? post_url(post) : posts_url %>" method="POST">
  <input type="hidden"
    name="_method"
    value="<%= post.persisted? ? "PATCH" : "POST" %>">
    
  <%= authenticity_token %>
  
  <label>Title
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  
  <label>URL
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  
  <label>Content
    <textarea name="post[content]"><%= post.content %></textarea>
  </label>
  
  <% subs.each do |sub| %>
    <label>
      <input type="hidden" name="post[sub_ids][]" value="">
      
      <input type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if post.sub_ids.include?(sub.id) %>>
      <%= sub.title %>
    </label>
  <% end %>
  
  <button><%= post.persisted? ? "Save" : "Create" %></button>
</form>

app/views/posts/edit.html.erb
<h3>Edit post</h3>

<%= render partial: "form", locals: { post: @post, subs: @subs } %>

app/views/posts/new.html.erb
<h3>Add post</h3>

<%= render partial: "form", locals: { post: @post, subs: @subs } %>

app/views/posts/show.html.erb
<!-- <h3><%#= link_to @post.sub.title, sub_url(@post.sub) %></h3> -->

<% if @post.author == current_user %>
  <%= link_to "Edit", edit_post_url(@post) %>
<% end %>
  
<h4><%= post_title(@post) %></h4>
<pre>
  <%= @post.content %>
</pre>

<%= render partial: "comments/form", locals: { post: @post, parent_id: nil } %>

<% @post.top_level_comments.each do |comment| %>
  <%= render partial: "comments/comment", locals: { comment: comment } %>
<% end %>